---
- name: Setup Vprofile Bastion Host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup Variable
      include_vars: vars/bastion_setup

    - name: Import VPC setup Variable
      include_vars: vars/output_vars

    - name: Create vprofile ec2 key
      ec2_key:
        name: vprofile-key
        region: "{{region}}"
      register: key_out
      
    - name: Save private key into file bastion-key.pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed
      
    - name: Create Sec Grp for bastion host
      ec2_group:
        name: Bastion-host-sg
        description: Allow port 22 from everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: BastionSG_out
      
    - name: Creating Bastion Host
      amazon.aws.ec2_instance:
        name: "Bastion_host"
        key_name: vprofile-key
        region: "{{region}}"
        instance_type: t2.micro
        image_id: "{{ bastion_ami }}"
        
        wait: yes
        wait_timeout: 300

        network:
          assign_public_ip: true        

        security_group: "{{BastionSG_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"

      register: bastionHost_out
      
    - debug:
        var: bastionHost_out.instances[0].public_ip_address

      
      
